arrowParens: 'avoid'
bracketSpacing: true
printWidth: 80
proseWrap: 'never'
semi: false
singleQuote: true
tabWidth: 2
trailingComma: 'none'
useTabs: false
jsxSingleQuote: true
overrides:
  - files: '*.md'
    options:
      semi: true